### ISSUE TITLE
Improvement to piece arrangement in the editor.

### ISSUE THREAD

**Issue by Curious2021** [gbtami/pychess-variants#852] opened 2022-02-12 02:50 UTC
When you play games in Pychess…you can click on a piece and the board lights up with circles showing where the pieces can be placed. When you click on the circle, the piece is automatically placed there. However, to place pieces in the editor…you have to drag them to place it onto the board. Why can’t the editor have the same ability as the game board?

**Comment by gbtami** [comment] 2022-02-15 09:07
This is duplicate of https://github.com/gbtami/pychess-variants/issues/395

**Closed by gbtami** 2022-02-15 09:07 UTC
Labels: duplicate
