### ISSUE TITLE
Game doesn't ends when random mover fags in shogi

### ISSUE THREAD

**Issue by SriMethan** [gbtami/pychess-variants#632] opened 2021-09-13 15:55 UTC
**how to reproduce - click practice with random mover and select minutes per side is 0 and byoyomy 2 seconds**
game url - https://www.pychess.org/RGV3oxxS **(The Game didn't end)**
![image](https://user-images.githubusercontent.com/77402282/133116562-3fa0bda6-c808-4112-a4ad-d72ad12d44b5.png)

**Comment by gbtami** [comment] 2021-09-13 20:14
This is duplicate of https://github.com/gbtami/pychess-variants/issues/211

**Closed by gbtami** 2021-09-13 20:14 UTC
