### ISSUE TITLE
Atomic explosions sound effects even after game is over.

### ISSUE THREAD

**Issue by Curious2021** [gbtami/pychess-variants#880] opened 2022-03-13 14:05 UTC
**Exact URL where the bug happened**

**Steps to reproduce the bug**
simply play a game in the atomic variant and after the game is over…wait and listen to the atomic sound explosions continue. 

**What did you expect to happen?**
once the game was over the atomic explosion sounds would end.
**What happened instead?**
atomic explosions continued after the game ended.
**Operating system and browser version**
doesn’t matter.

**Comment by gbtami** [comment] 2022-03-13 14:40
I can't reproduce this. Can you provide a short video clip to let me see how it is going for you please?

**Comment by Curious2021** [comment] 2022-03-13 18:54
i don’t know how to video record a sound after a game is over. i can tell you this issue is similar to the one about sound effects going off after you reconnect to the game after being disconnected. it’s similar to that issue but in this case it was happening after the game finished but before i could switch over to a different game.

**Comment by gbtami** [comment] 2022-03-13 19:33
Is this reproducible for you? I mean it happens all in your atomic games?

**Comment by CouchTomato87** [comment] 2022-03-13 20:57
I think this is the same issue for any completed game, where randomly you'd hear the last move sound again. I assume because of reconnection or something? It's not unique to atomic though

**Comment by gbtami** [comment] 2022-03-13 22:39
Thx. This is duplicate of https://github.com/gbtami/pychess-variants/issues/734 then.

**Closed by gbtami** 2022-03-13 22:39 UTC
Labels: bug, duplicate
