### ISSUE TITLE
Analysis bar gone

### ISSUE THREAD

**Issue by CouchTomato87** [gbtami/pychess-variants#120] opened 2020-01-23 01:20 UTC
https://pychess-variants.herokuapp.com/peqq8tNU

I can't see the white-black analysis bar on the side.

**Comment by gbtami** [comment] 2020-01-23 08:22
Refresh your browser page, please!

**Comment by CouchTomato87** [comment] 2020-01-23 12:48
I did, wiped my cookies etc. Still doesn't show up... I'm talking about the thermometer-like bar on the right of the board, not the graph

**Comment by gbtami** [comment] 2020-01-23 14:01
Works for me. Maybe you have to clear browser cache also.
![http://i.imgur.com/UmKtpNq.png](http://i.imgur.com/UmKtpNq.png)

**Comment by gbtami** [comment] 2020-01-24 11:42
Reproduced on Chromium.

**Comment by gbtami** [comment] 2020-01-24 11:58
Fixed by https://github.com/gbtami/pychess-variants/commit/8e08ec26636cd457e9007c70279f030af4fa4555

**Closed by gbtami** 2020-01-24 11:58 UTC
Labels: bug
