### ISSUE TITLE
Castling kingside not working in capablanca chess

### ISSUE THREAD

**Issue by ianfab** [gbtami/pychess-variants#1] opened 2019-07-04 19:43 UTC
Castling kingside in capablanca chess does not work (with either color), whereas on the queenside there apparently is no such issue.

**Comment by gbtami** [comment] 2019-07-05 07:31
It's interesting that I was able to O-O in first couple of games, but finally reproduced it.

**Comment by gbtami** [comment] 2019-07-05 13:18
I'v added some debug print() at https://github.com/gbtami/pychess-variants/blob/master/fairy.py#L48 to see what's happening and got this:
```
self.move_stack: ['a2a4', 'f7f5', 'b2b3', 'g8d5', 'b1a3', 'i8h6', 'c1a2', 'h8g6', 'c2c4']
legal_moves: ['f5f4', 'a7a6', 'b7b6', 'c7c6', 'd7d6', 'e7e6', 'i7i6', 'j7j6', 'a7a5', 'b7b5', 'c7c5', 'e7e5', 'i7i5', 'j7j5', 'b8a6', 'b8c6', 'h6g4', 'h6i4', 'h6j5', 'h6f7', 'h6g8', 'h6i8', 'd5g2', 'd5f3', 'd5c4', 'd5e4', 'd5c6', 'd5e6', 'd5f7', 'd5g8', 'j8g8', 'j8h8', 'j8i8', 'e8f7', 'c8b6', 'c8d6', 'g6g2', 'g6g3', 'g6f4', 'g6g4', 'g6h4', 'g6e5', 'g6g5', 'g6i5', 'g6a6', 'g6b6', 'g6c6', 'g6d6', 'g6e6', 'g6f6', 'g6h8', 'f8f7', 'f8g8']
```
This is rather strange because Fairy-Stockfish Python binding test with this same move list is OK.
https://github.com/gbtami/Fairy-Stockfish/blob/master/test.py#L45

I'm a little bit stucked here.

**Comment by gbtami** [comment] 2019-07-07 09:51
I'v extended capablaca king side castling unit test to turn it a very simple stress test.
``` python
    def test_short_castling(self):
        for i in range(10000):
            print(i)
            moves = ['a2a4', 'f7f5', 'b2b3', 'g8d5', 'b1a3', 'i8h6', 'c1a2', 'h8g6', 'c2c4']
            result = sf.legal_moves("capablanca", CAPA, moves)
            self.assertIn("f8i8", result)

            moves = ['f2f4', 'g7g6', 'g1d4', 'j7j6', 'h1g3', 'b8a6', 'i1h3', 'h7h6']
            result = sf.legal_moves("capablanca", CAPA, moves)
            self.assertIn("f1i1", result)
```
The tail of result:
```
6559
6560
6561
6562
6563
6564
6565
F.
======================================================================
FAIL: test_short_castling (__main__.TestPyffish)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 50, in test_short_castling
    self.assertIn("f8i8", result)
AssertionError: 'f8i8' not found in ['f5f4', 'a7a6', 'b7b6', 'c7c6', 'd7d6', 'e7e6', 'i7i6', 'j7j6', 'a7a5', 'b7b5', 'c7c5', 'e7e5', 'i7i5', 'j7j5', 'b8a6', 'b8c6', 'h6g4', 'h6i4', 'h6j5', 'h6f7', 'h6g8', 'h6i8', 'd5g2', 'd5f3', 'd5c4', 'd5e4', 'd5c6', 'd5e6', 'd5f7', 'd5g8', 'j8g8', 'j8h8', 'j8i8', 'e8f7', 'c8b6', 'c8d6', 'g6g2', 'g6g3', 'g6f4', 'g6g4', 'g6h4', 'g6e5', 'g6g5', 'g6i5', 'g6a6', 'g6b6', 'g6c6', 'g6d6', 'g6e6', 'g6f6', 'g6h8', 'f8f7', 'f8g8']

----------------------------------------------------------------------
Ran 11 tests in 2.418s

FAILED (failures=1)
tamas@tami:~/Fairy-Stockfish$
```
It is possible that https://github.com/gbtami/Fairy-Stockfish/blob/master/src/pyffish.cpp#L194 has a bug :(

**Comment by ianfab** [comment] 2019-07-08 07:38
Thanks for debugging it, I will check whether the bug is my code.

**Comment by gbtami** [comment] 2019-07-23 11:46
It occurred in standard chess also so it's not related to capablanca. I'm 99.99% sure my Python bindings has a bug somewhere. Unfortunately I'm rookie in C++.
http://i.imgur.com/T59Iul8.png

**Comment by gbtami** [comment] 2019-07-24 09:18
Fixed via https://github.com/gbtami/Fairy-Stockfish/commit/850e4f5e8aad4d5bc129f8d47ff91c575a9683ae

**Closed by gbtami** 2019-07-24 09:18 UTC
Labels: bug, help wanted
