### ISSUE TITLE
Shogi pieces flipped

### ISSUE THREAD

**Issue by CouchTomato87** [gbtami/pychess-variants#146] opened 2020-02-14 21:28 UTC
Apparently using the browser's dark mode will make the shogi pieces flip direction.

**Comment by gbtami** [comment] 2020-02-14 21:52
Can you describe step-by-step how can I reproduce this, please?

**Comment by CouchTomato87** [comment] 2020-02-15 00:32
"I use a 'dark mode everywhere' plugin on Chrome! I think pychess orients the pieces based on the colour of sente and gote circles.. because the plugin reverses black and white, the pieces face the opposite directions! if you have the same problem just disable it and refresh"

**Comment by gbtami** [comment] 2020-02-15 08:26
I think plugins has nothing to do with this issue at all. Here is my try using "Dark Theme for Chrome". (I can't find "dark mode everywhere" plugin.)
![http://i.imgur.com/iVMgEE9.png](http://i.imgur.com/iVMgEE9.png)
@Fulmene can you help me to reproduce this, please?

**Comment by Fulmene** [comment] 2020-02-15 12:55
I used the extension called "Dark Reader" back when I faced it. However I can't reproduce it now. This might actually be the issue about how the extension handles chess colours, and not the fault of Pychess.

I used to have an issue of missing pieces when I used Dark Reader on Lichess too. I can't reproduce it now either.

**Comment by gbtami** [comment] 2020-02-15 13:12
Thx. I close this now, but feel free to reopen if you face it again.

**Comment by CouchTomato87** [comment] 2020-02-15 15:47
I was able to reproduce it... https://chrome.google.com/webstore/detail/dark-reader/eimadpbcbfnmbkopoojfekhnkhdbieeh/related

And the issue only happens when you're on the light mode here and you use sente/white.

**Closed** 2020-02-15 16:05 UTC
Labels: bug, wontfix
