### ISSUE TITLE
Pychess editor board does not recognize chess960 rules for the rooks.

### ISSUE THREAD

**Issue by Curious2021** [gbtami/pychess-variants#746] opened 2022-01-02 12:49 UTC
Manually creating FEN positions using Chess960 rules is not allowed using the Editor. If you try generating a valid FEN position with the rooks placed anywhere else than their standard setup using chess960 rules the position is deemed an error. It only recognizes chess960 positions where the rooks remain on their original squares. Pychess will only let you generate valid chess960 positions with the rooks in nonstandard setups from the lobby only. This is a serious bug that needs fixing.

**Comment by Curious2021** [comment] 2022-01-02 16:35
Additional information about this bug. Apparently you can setup the board manually in any chess960 position and be recognized as valid using the editor IF you clear the board and place the pawns and kings FIRST. Then you can place the rooks anywhere following chess960 rules and the editor recognizes the position as valid. However, if you then select the checkmarks next to the castling options using chess960 rules, the editor immediately deems the position to be invalid even though the editor marked the position as valid prior to ticking off the checkmarks for castling. There is a programming logic flaw in the code which is causing this error.

**Comment by gbtami** [comment] 2022-02-23 23:12
This is duplicate of https://github.com/gbtami/pychess-variants/issues/554

**Closed by gbtami** 2022-02-23 23:12 UTC
Labels: duplicate
