### ISSUE TITLE
Tapping on pieces in pockets with Apple Pencil for placement doesn’t get recognized.

### ISSUE THREAD

**Issue by Curious2021** [gbtami/pychess-variants#870] opened 2022-03-03 06:17 UTC
**Exact URL where the bug happened**

**Steps to reproduce the bug**
Using Apple Pencil to tap on pieces in pockets doesn’t get recognized for piece placement.
**What did you expect to happen?**
when i tap on pieces in pockets for placement there are circles which light up telling me where to place that piece.
**What happened instead?**
The board refuses to recognize i tapped on the piece in the pocket for placement and no circles are visible when this happens. but when i use my finger…the piece gets recognized and the circles light up on the board. you have to drag the piece with the Apple Pencil to get the platform to recognize there’s an input device being used to place that piece on the board.
**Operating system and browser version**
Apple ios 15.1.3

**Comment by gbtami** [comment] 2022-03-03 09:30
Is this works on lichess.org ?

**Comment by Curious2021** [comment] 2022-03-03 23:32
No…but this is supposed to work in pychess because pychess allows it. lichess doesn’t light up the board when placing pieces using the editor. does that mean pychess is doing it incorrectly by allowing the board to light up when placing pieces using the editor? i think not. but that’s your call.

**Comment by gbtami** [comment] 2022-03-03 23:41
This is duplicate of https://github.com/gbtami/pychess-variants/issues/612

**Closed by gbtami** 2022-03-03 23:41 UTC
Labels: duplicate
