### ISSUE TITLE
unselecting "show piece destinations" checkbox doesn't make it stop showing possible drop destinations

### ISSUE THREAD

**Issue by Olekaze** [gbtami/pychess-variants#940] opened 2022-05-14 22:12 UTC

**Comment by gbtami** [comment] 2022-05-14 23:11
Works for me. Provide steps to reproduce, please.

**Comment by Olekaze** [comment] 2022-05-14 23:18
play any varient with drops, turn off show piece destinations, take one of your opponent's pieces, when you drag it from your piece pocket it shows you all the possible squares you can drop it in

**Comment by gbtami** [comment] 2022-05-14 23:26
Works for me:
![https://i.imgur.com/baLXuSX.png](https://i.imgur.com/baLXuSX.png)

**Comment by Olekaze** [comment] 2022-05-14 23:32
try refreshing it with the option off, selecting and unselecting it temporarily fixes it

**Comment by Olekaze** [comment] 2022-05-14 23:34
![Screenshot 2022-05-14 19 33 30](https://user-images.githubusercontent.com/89757188/168451318-f0903c56-9cb8-46dd-b104-24f4236611c7.png)

**Comment by gbtami** [comment] 2022-05-14 23:45
I reproduced it now. Thx!

**Comment by Fulmene** [comment] 2022-08-15 14:38
Fixed by #992

**Closed by Fulmene** 2022-08-15 14:38 UTC
Labels: bug
