### ISSUE TITLE
Shogi notation slightly wrong

### ISSUE THREAD

**Issue by CouchTomato87** [gbtami/pychess-variants#17] opened 2019-08-21 10:53 UTC
Just realized this when testing pieces. Western shogi notation usually depicts promotion with a + at the end of the move. While this usually means "check" in chess, shogi doesn't depict checks. However, the notation here uses + for check, but does not indicate when a piece promotes (which is more important).

**Comment by gbtami** [comment] 2019-08-21 21:34
It should be better now. I'v added + prefix for promoted piece moves, but I'm not sure about this.
Can you check is it OK now, please?

**Comment by CouchTomato87** [comment] 2019-08-21 21:39
I just checked using this game: https://pychess-variants.herokuapp.com/s3Ow7v96

All promoted minor pieces now say +G for some reason. They should be +P, +N, +L, +S for the pawn, knight, lance, and silver, respectively.

Also, the dragon king is noted as "+D"  while the dragon horse is noted as "+H". This is redundant, as D and H already means promoted, so you just need D instead of +D. Similar, the dragon horse should just be an H instead of +H.

**Comment by ianfab** [comment] 2019-08-21 21:44
If you want to resolve the unpromoted piece types to get the correct prefix `Position::unpromoted_piece_on` might be useful. I guess the ambiguity resolution will then become quite complex, because you need to first identify the unpromoted piece type of all "golds" (promoted or unpromoted pieces) in order to find out whether there is more than one promoted piece of the same type that can move to a square.

**Comment by gbtami** [comment] 2019-08-21 22:02
@CouchTomato87 thx for the quick test!
@ianfab thx for the suggestions!

**Comment by gbtami** [comment] 2019-08-21 23:06
@CouchTomato87 committed another fix. Can you test it again, please?

**Comment by CouchTomato87** [comment] 2019-08-21 23:11
It works now. :) The dragon and horse now use +R and +B, which is an acceptable alternative to D and H.

**Comment by gbtami** [comment] 2019-08-22 07:34
OK, the only issue now is some remaining unnecessary disambiguation (12... +N9g9h in above game) caused by these "golds". Hints by ianfab are given. It is just needs implementation.

**Comment by CouchTomato87** [comment] 2019-08-22 10:55
Ah sorry, I forgot to check for disambiguation!

**Comment by CouchTomato87** [comment] 2019-08-23 21:49
I just did some more research on notation, and there's two main ones in use: the older Hodges notation and the newer Hosking notation. We are currently using Hodges, which is why I thought it was okay, but there are some inconsistencies. And since you were planning different notation options anyways, it may be worth trying both.

*Updates for Hodges*

-Hodges uses a - for each move. For example, P-5e. This is not currently implemented.
-Both systems use "=" if a piece chooses NOT to promote when it can. For example, pawn to 1c without promotion is P-1c=. This is currently not implemented. 
-For disambiguation, both systems use the piece origin, followed by a -, followed by destination. So for example in the starting position, black moving his right gold in front of a king would be G4i-5h. Currently, this uses the chess style of "G45h".

The main differences for *Hosking* is:
-Coordinates are BOTH numbers. So 4c would be 43
-Also, movement often does not use a -. A pawn moving to 4c would be P43 (similar to how it is done currently).
-For disambiguation, it does the same as Hodges. So in the example above, that gold move would be G49-58.

**Comment by CouchTomato87** [comment] 2019-08-26 01:25
For what it's worth, it seems that the Hosking style (two numbers) is more prevalent nowadays (since Ian brought this up in the chat).

**Comment by gbtami** [comment] 2019-08-26 07:50
At some point we should offer Hodges/Hosking/Native radio button on preferences panel which can change the board coordinates also.
(At this moment only the zoom slider is implemented there.)

**Comment by ianfab** [comment] 2019-08-26 18:59
@gbtami @CouchTomato87 Since it is more compatible with the USI protocol and therefore easier to implement, I started with Hodges notation in https://github.com/gbtami/Fairy-Stockfish/pull/3. From what I have seen both notations are quite similar in popularity, so we can add Hosking as a configurable option at a later point.

**Comment by gbtami** [comment] 2019-08-28 08:11
Filed new issue https://github.com/gbtami/pychess-variants/issues/22 for other options.

**Closed by gbtami** 2019-08-28 08:11 UTC
Labels: bug
