### ISSUE TITLE
Gated pieces not visible until opponent makes move. 

### ISSUE THREAD

**Issue by Curious2021** [gbtami/pychess-variants#376] opened 2020-11-19 15:43 UTC
Gated pieces in S-Chess and others not appearing immediately until after opponent makes a move. Here's an example of the issue. So if White makes a move that allows a piece in hand to appear on the board it should appear immediately but is not visible. After the opponent makes a move the prior location of the previous move made shows a gated piece appear on the square it should have appeared on its previous move. I cannot reliably demonstrate this bug but needed to notify the administrators of what I'm experiencing.

**Comment by gbtami** [comment] 2020-11-19 16:38
I can't reproduce this. Can you provide a short video recording to demonstrate it, please?

**Comment by Curious2021** [comment] 2020-11-19 18:32
I don't know how to make videos for something like this as I don't screencast my games. But this as I me to ones can't be reliably duplicated. In order to catch the problem I'd have to screencapture every game I play in order to catch the moment this issue happens. But I'm not imagining it. This is something that's been frustrating me for a while. At first I thought I was imagining this. But then I started to noticed gated pieces appearing on squares I thought had been empty. Thats not a good sign.

**Comment by gbtami** [comment] 2020-11-19 20:36
All I can suggest is to create a screenshot/photo when it happens next time. Of course it is hard if your opponent moves immediately :(

**Comment by Curious2021** [comment] 2020-11-19 22:49
I'll keep an eye on this elusive bug and I'll see if I can take snapshots of the issue when I see it. But video might be impossible to do because this puts me in the position of having to screencast all my games.  Not a very viable solution.

**Comment by gbtami** [comment] 2020-11-19 23:02
Btw. is this happened on Safari only? I'm asking this because I test on Chrome, Firefox, Edge, Opera. I have no Apple device at all.

**Comment by gbtami** [comment] 2020-12-02 17:26
Maybe we should try to reproduce this issue playing some S-chess game with each other. Ping me on Discord if you have time for some more testing please!

**Comment by gbtami** [comment] 2021-03-31 09:28
I'm closing this now. Feel free to reopen if it happens again.

**Closed by gbtami** 2021-03-31 09:28 UTC
