### ISSUE TITLE
Display Tournament standings and remaining time in Game play

### ISSUE THREAD

**Issue by visualdenniss** [gbtami/pychess-variants#730] opened 2021-12-19 17:43 UTC
It can be useful, if the players can see the live tournament standings and remaining time during the game. That would also prevent, having to open another tab during the game to look and then forget that you have two tabs open and lose games later cuz the game started on another tab and you don't even notice.. Thanks :)

**Comment by gbtami** [comment] 2021-12-19 21:06
We should try the same like lichess ![https://i.imgur.com/MHyZs98.png](https://i.imgur.com/MHyZs98.png)

**Comment by gbtami** [comment] 2021-12-21 11:13
Just recognised that this is a duplicate of https://github.com/gbtami/pychess-variants/issues/558 :)

**Closed by gbtami** 2021-12-21 11:13 UTC
Labels: enhancement
