### ISSUE TITLE
Rematch button freezes after completing a couplet in S-Chess960

### ISSUE THREAD

**Issue by Curious2021** [gbtami/pychess-variants#407] opened 2020-12-09 14:23 UTC
After completing a couplet (white and black games of one randomized setup) S-Chess refused to respond after requesting a rematch which would supposedly offer a new setup position to play. Had to refresh the browser window and had to re-enter webpage and selected “new opponent” to restart the process.

**Comment by gbtami** [comment] 2020-12-09 16:33
I cant reproduce this. I can imagine that your connection had issues. Or is this reproducible for you?

**Comment by Curious2021** [comment] 2020-12-09 18:17
I’m keeping an eye on this one. If I experience it again I’ll report it again in this thread. I’m in the middle of a couplet right now. If I have a problem creating a new setup after I complete the second game that would confirm it.

**Comment by gbtami** [comment] 2021-03-18 09:33
I'm closing this, but if you can reproduce it feel free to reopen.

**Closed** 2021-03-18 09:32 UTC
