### ISSUE TITLE
Capablanca chess board too big for mobile phones. 

### ISSUE THREAD

**Issue by Curious2021** [gbtami/pychess-variants#375] opened 2020-11-19 12:14 UTC
Capablanca chess board does not orient itself correctly to small screen sizes using mobile phones. In order to see the pieces on the screen you have to scroll and pan to reach the piece you want to move using your iPhone. This issue doesn't manifest if you're using a laptop/tablet. Only mobile phones.

**Comment by gbtami** [comment] 2020-11-19 14:42
Duplicate of https://github.com/gbtami/pychess-variants/issues/6

**Closed by gbtami** 2020-11-19 14:42 UTC
