### ISSUE TITLE
Random Mover option in dialog box instead of separate menu item.

### ISSUE THREAD

**Issue by Curious2021** [gbtami/pychess-variants#911] opened 2022-04-10 15:43 UTC
Put the random mover option in the dialog box when the player chooses a variant to play. This way the player can choose to play against Random Mover instead of Fairy Stockfish if she or he wants. Liantichess just implemented this on their fork site and thought this would be a nice enhancement for Pychess.

**Comment by gbtami** [comment] 2022-04-10 16:07
Duplicate of https://github.com/gbtami/pychess-variants/issues/680

**Closed by gbtami** 2022-04-10 16:07 UTC
Labels: duplicate
